version: '3.8'

## CAUTION: Please ensure you edit the following environment files before running this Docker Compose file:
# 1. with-db.env
# 2. postgres.env (If using External DB and/or LogTo)
# 3. logto.env (If using LogTo)

# SYNTAX: docker compose -f docker/with-external-db/docker-compose-with-db.yml up --detach

services:
    app:
        # To change the image version, edit the ":latest" tag to the desired version
        # For production/stable release, use ":latest"
        # For development/staging release, use ":staging-latest"
        image: originvault/cheqd-studio:latest
        ports:
            - 3000:3000
        env_file:
            - ~/cheqd-studio.env
        healthcheck:
            test: ['CMD', 'wget', '--quiet', '--spider', 'http://localhost:3000/swagger']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - logto-network

    # This service is used as a ONE-TIME setup service to run migrations
    # Only relevant if you're using the app with EXTERNAL_DB=true
    # app-migrations:
    #     image: originvault/cheqd-studio:latest
    #     env_file:
    #         - ~/cheqd-studio.env
    #     entrypoint: ['npm', 'run', 'migrate']
    #     profiles:
    #         - app-setup
    #         - external-kms

networks:
    logto-network:
        external: true
