name: "Build"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build Node.js"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '14.x', '16.x' ]
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: "Execute build for Node v${{ matrix.version }}"
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run build
